# Generated by Django 5.1.7 on 2025-03-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("univs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="university_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="univs.university",
            ),
        ),
    ]
