# Generated by Django 5.1.7 on 2025-04-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("univs", "0002_alter_user_university_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(max_length=255, null=True, upload_to="\\media"),
        ),
        migrations.AlterField(
            model_name="admissionevaluation",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="university",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
